- src/aleph_client/asynchronous.py
- src/aleph_client/chains/common.py
- src/aleph_client/chains/cosmos.py
- src/aleph_client/chains/ethereum.py
- src/aleph_client/chains/nuls1.py
- src/aleph_client/chains/nuls2.py
- src/aleph_client/chains/substrate.py
- tests/test_chain_ethereum.py
- tests/test_chain_nuls1.py
- tests/test_chain_nuls1_compat.py
In preparation for handling private keys remotely through APIs.
> Refactor: Make sign and decrypt asynchronous

- setup.cfg
- src/aleph_client/chains/common.py
- src/aleph_client/chains/sol.py
- tests/test_chain_ethereum.py
- tests/test_chain_nuls1_compat.py
- tests/test_chain_solana.py
GM!
Added solana support with according tests. Tests are modeled after the verification process in pyaleph's https://github.com/aleph-im/pyaleph/blob/master/src/aleph/chains/solana.py. Added pynacl as core dependency and base58 as solana-specific. Please verify that the setup still works for you.
> Add solana support

- setup.cfg
> Hotfix²: Add pynacl to testing requirements

- src/aleph_client/chains/common.py
> Hotfix³: Make tests pass again

- docker/Dockerfile
- setup.cfg
- src/aleph_client/vm/app.py
- tests/test_app/main.py
- tests/test_vm_app.py
Fixes https://github.com/aleph-im/aleph-vm/issues/96
> Fix: AlephApp wrapper was not compatible with Uvicorn

- src/aleph_client/asynchronous.py
Added a new `content_keys` parameter to `get_messages` to filter
messages by their content key, if specified.
> [Messages] Add content keys parameter

- README.rst
- docker/Dockerfile
- scripts/build-and-shell.sh
- scripts/build-and-test.sh
- src/aleph_client/chains/common.py
- src/aleph_client/chains/cosmos.py
- src/aleph_client/chains/sol.py
- src/aleph_client/chains/substrate.py
- src/aleph_client/conf.py
- tests/unit/test_asynchronous.py
Only define it in conf.settings.
> Refactor: Two origins for PRIVATE_KEY_FILE were confusing

- src/aleph_client/__main__.py
- src/aleph_client/asynchronous.py
- src/aleph_client/chains/cosmos.py
- src/aleph_client/chains/nuls1.py
- src/aleph_client/chains/nuls2.py
- src/aleph_client/chains/remote.py
- src/aleph_client/chains/sol.py
- src/aleph_client/chains/substrate.py
- src/aleph_client/chains/tezos.py
- src/aleph_client/conf.py
- src/aleph_client/utils.py
- src/aleph_client/vm/app.py
- src/aleph_client/vm/cache.py
- tests/integration/conftest.py
- tests/unit/test_asynchronous.py
- tests/unit/test_chain_tezos.py
A collection of small changes and fixes.
> Code cleanup

- src/aleph_client/asynchronous.py
For `get_posts()` and `get_messages()`
> add param for getting posts by chains

- src/aleph_client/__main__.py
Due to refactoring to return objects instead of dicts.
> Fix: Update command was broken

- src/aleph_client/__main__.py
- src/aleph_client/account.py
- src/aleph_client/chains/common.py
- src/aleph_client/chains/cosmos.py
- src/aleph_client/chains/ethereum.py
- src/aleph_client/chains/sol.py
- src/aleph_client/chains/tezos.py
- src/aleph_client/conf.py
- src/aleph_client/types.py
This refactors the structure of the helper `_load_account` used in the CLI and adds backend support for Solana and Thezos accounts.
> Feature: Add backend support for Solana,Tezos in _load_account

- src/aleph_client/vm/cache.py
- tests/unit/test_vm_cache.py
Problem: Programs that work on Aleph VMs and use VmCache cannot work locally
Solution: Introduce abstract base class for VmCache and implement LocalVmCache to mock VmCache functionality
> Feat: Add LocalVmCache for testing purposes

- src/aleph_client/__main__.py
- src/aleph_client/chains/common.py
- src/aleph_client/chains/ethereum.py
- src/aleph_client/chains/sol.py
- src/aleph_client/chains/tezos.py
- src/aleph_client/commands/account.py
- src/aleph_client/conf.py
- tests/unit/conftest.py
- tests/unit/test_asynchronous.py
- tests/unit/test_chain_ethereum.py
- tests/unit/test_chain_nuls1_compat.py
- tests/unit/test_chain_solana.py
- tests/unit/test_chain_tezos.py
> Store the private key in the user's home instead of the current directory

- src/aleph_client/vm/app.py
The support of this scope is required for https://github.com/aleph-im/aleph-vm/pull/295
> Fix: ASGI 'lifespan' scope was not supported

- src/aleph_client/commands/files.py
- tests/unit/test_commands.py
Solutions:
Create a new command that allows users to download a file from a hash.
> Feature: download File

- setup.cfg
puls2-python is broken
change dependency to aleph-nuls2
> Aliel fix nuls2 deps

- src/aleph_client/commands/message.py
Problem: 
- The message wasn't sent as an amend.
- The time sent corresponds to the original message time and not current.
> Fix: Amend Function

- src/aleph_client/commands/instance.py
- src/aleph_client/commands/utils.py
- src/aleph_client/conf.py
Improvements:
- Use `rich` more broadly in instances and `utils.py`
- Add `aleph instance list` command
- Improve `aleph instance create` to be easier to understand and more interactive
- Add fresh Ubuntu 22, Debian 11 and Debian 12 rootfs item hashes to choice
> Improve Instance Creation and Add `instances list`

- src/aleph_client/commands/program.py
>  * Fix CLI regression

- docs/content/aggregates.rst
- docs/content/posts.rst
- src/aleph_client/__init__.py
- Raising ImportError for common imports like `aleph_client.AlephClient` or `aleph_client.asynchronous`
- Update docs for aggregate and posts
> Add deprecation messages and update docs

- src/aleph_client/commands/domain.py
- src/aleph_client/commands/help_strings.py
Problem: SPA application needs special settings on DNS resolution service to be loaded well.
Solution: Add the SPA field on the domain aggregate to note that is an SPA application.
> Add SPA field on domains

- src/aleph_client/commands/node.py
- **refactor: remove unused variable**
- **fix(node): add missing return type annotation**
> fix(node): add missing return type annotation

- .github/workflows/pytest.yml
- pyproject.toml
> Attempt to fix Codecov - it does not work in this repo

- src/aleph_client/commands/instance/__init__.py
if an user passed the --hypervisor option, the question was still asked
> Problem: Hypervisor passed in parameter was not respected

- .github/PULL_REQUEST_TEMPLATE.md
As discussed, providing these informations on each PR should improve review and code quality
> Provide a template for new PRs

- src/aleph_client/commands/help_strings.py
- src/aleph_client/commands/instance/__init__.py
Problem:
We currently blocking user from creating Confidential vm using hold method. However, in the case user use NFT he need to set the payment type to Hold.
> Feature: prompt for payment type

- src/aleph_client/commands/instance/__init__.py
Fix two bug. A crash if one of the instance was unreachable and return the proper ipv6
- [na ] New classes and functions contain docstrings explaining what they provide.
- [na] All new code is covered by relevant tests.
- [na] Documentation has been updated regarding these changes.
N/A
Have instances created and run `aleph instance list`
> Fix IPv6 in instance list + fix crash

- .github/PULL_REQUEST_TEMPLATE.md
Explain what problem this PR is resolving
The Pull Request template did not put enough emphasis on the documentation
_No code is impacted_
A new section in the Pull Request template asks for what documentation is impacted and for the diff.
Open a Pull Request on this project.
> Update PR template with details on documentation

- README.md
- docs/content/async_notes.rst
- docs/content/introduction.rst
- src/aleph_client/commands/domain.py
fix some comments
The documentation regarding the impacted features is available on:
> URL
The changes in the documentation are available here:
> URL
Explain the changes that were made. The idea is not to list exhaustively all the changes made (GitHub already provides a full diff), but to help the reviewers better understand:
- which specific file changes go together, e.g: when creating a table in the front-end, there usually is a config file that goes with it
- the reasoning behind some changes, e.g: deleted files because they are now redundant
- the behaviour to expect, e.g: tooltip has purple background color because the client likes it so, changed a key in the API response to be consistent with other endpoints
Explain how to test your PR.
If a specific config is required explain it …
> chore: fix some comments

- src/aleph_client/commands/account.py
- src/aleph_client/commands/instance/__init__.py
UX changes inside orange squares:
> Feature: improve UX for price flow and balance

- .github/dependabot.yml
- .github/workflows/code-quality.yml
- .github/workflows/pr-rating.yml
- .github/workflows/pytest.yml
- .github/workflows/test-build.yml
- .github/workflows/test-docker.yml
- pyproject.toml
Enable [yamlfix](https://github.com/lyz-code/yamlfix) to auto format yaml files.
Related ClickUp, GitHub or Jira tickets : ALEPH-176
Run:
```
hatch run linting:all
```
Or:
```
hatch run linting:fmt
```
> feat: add yamlfix

- pyproject.toml
> feat: add pyproject-fmt

- src/aleph_client/commands/instance/__init__.py
- src/aleph_client/commands/instance/display.py
Solved error messages showing the CRN list for GPUs and also added the GPU sort and filter.
Fixed gpu filter on CRN table display and also added the sorting key.
Try to create an instance with a GPU attached using the command `aleph instance create --gpu`
> Solve GPU list display issues

- tests/unit/test_commands.py
> run tests on testnet to avoid spam on mainnet

- pyproject.toml
- src/aleph_client/commands/account.py
> fix: mypy wasn't taking pyproject.toml into account

- .github/workflows/pytest.yml
- .github/workflows/test-build.yml
- pyproject.toml
Other version of python are deprecated and this will allow us to use new features.
See https://www.python.org/downloads/
> feat: only support stable version of python (>=3.9)

- src/aleph_client/commands/account.py
- src/aleph_client/commands/domain.py
- src/aleph_client/commands/files.py
- src/aleph_client/commands/instance/__init__.py
- src/aleph_client/commands/message.py
- src/aleph_client/commands/node.py
- src/aleph_client/commands/program.py
- tests/unit/test_commands.py
- Wrap all command args in Annotated to allow to easily import CLI as a lib
> Fix: Wrap all command args in Annotated

- src/aleph_client/commands/account.py
This PR allow new SVM Chain private key to get parsed as SOLANA chain
> Feature: new SVM chain should parse as sol

- src/aleph_client/commands/account.py
- src/aleph_client/commands/instance/__init__.py
- src/aleph_client/voucher.py
- tests/unit/test_voucher.py
On aleph-client we never really handle Vouchers we only accept it as args and trust the input,
now we want to be able to fetch Vouchers to ensure user have it .
Related ClickUp, GitHub or Jira tickets : ALEPH-458 (This feature is missing for this tickets)
This pull request introduces a new `VoucherManager` class and associated functionality to manage and display voucher information within the `aleph_client`. It enhances the `balance` command to show voucher details, adds a new `vouchers` command for detailed voucher information, and integrates voucher handling into the instance creation process. Additionally, a new `voucher.py` file implements the core logic for fetching and processing vouchers.
* **New `VoucherManager` Class**: Added `voucher.py` to handle voucher-related operations, …
> Feature: Voucher implémentations

- src/aleph_client/commands/instance/network.py
Fix: Relax CRN version check to use custom versions.
Removed strict check that was using GitHub release to check the CRNs.
Try to create a confidential or PAYG instance after a release and see that some CRNs appears.
This is a quick fix to allow users to create PAYG instance. **TODO:** We need to improve it to use the settings aggregate for example.
> Relax CRN version check to use custom version

- pyproject.toml
Feature: Upgrade SDK to `2.1` version and `aleph_message` to `1.0.5` version.
Upgrade SDK to `2.1` version and `aleph_message` to `1.0.5` version.
Try to execute basic commands like list instances and check that works.
> Upgrade SDK and `aleph_message` versions
