aleph-im/aleph-client

README.rst
The `aleph-client` library on PyPI points to this repository, but there was no reference to it from this repository.
A user could not be sure that the package on PyPI was backed by the Aleph.im team.
=> Confirm that aleph-client on PyPI is official

src/aleph_client/asynchronous.py
Server errors were causing difficult to understand errors. This change makes HTTP requests raise an exception if the response status code is not OK.
=> Fix: Raise exception when HTTP status code not OK

src/aleph_client/__main__.py, src/aleph_client/chains/remote.py, src/aleph_client/conf.py, tests/test_remote_account.py
For use in virtual machines or other contexts where the private key is not immediately available.
=> Feature: Add support for remote account via HTTP API

src/aleph_client/chains/common.py, src/aleph_client/chains/cosmos.py, src/aleph_client/chains/ethereum.py, src/aleph_client/chains/nuls1.py, src/aleph_client/chains/nuls2.py, src/aleph_client/chains/remote.py, src/aleph_client/chains/substrate.py, tests/test_chain_ethereum.py, tests/test_remote_account.py
This enforces that the account signing the message has it's public key marked as sender of the message.
=> Fix: A signature could not match the message's sender field

src/aleph_client/__main__.py
fix mksquashfs to avoid append file instead of overwrite it if squashfs file exists
=> fix mksquashfs to avoid append file instead of overwrite it

src/aleph_client/asynchronous.py
Submit requires JSON serializable dict, the create_aggregate call is missing the change.
=> Fix JSON serialization in aggregate creation

src/aleph_client/asynchronous.py
Params fixed in:
- get_messages
- get_posts
- watch_messages
=> Fixes typo on startDate and endDate filter params name

tests/unit/test_asynchronous_get.py
Since the introduction of resource nodes
=> Fix: Tests were failing due to new node type

src/aleph_client/asynchronous.py
This query param is required for large aggregates such as the list of nodes.
=> Fix: Aggregate 'limit' query param could not be specified

src/aleph_client/__main__.py
Added a new command, `whoami`, to return the public address
of the user from the command line.
=> [User ID] whoami command

setup.cfg, src/aleph_client/__main__.py, src/aleph_client/asynchronous.py, src/aleph_client/synchronous.py, tests/unit/test_asynchronous.py, tests/unit/test_asynchronous_get.py
These changes break the API and make it return models from Aleph-message instead of Python dictionaries.
=> Return models instead of dictionaries

docker/with-ipfs.dockerfile
Solution: Upgrade go-ipfs 0.7.0 to kubo (new name of the project) 0.15.0
=> Update: Container uses old go-ipfs 0.7 while 0.15 is available

src/aleph_client/asynchronous.py
Problem: Python client returns Messages with different item_hash from what is seen on Aleph Explorer:
Solution: Remove double calculation of item_hash introduced in PR #74
=> Fix: Received item_hash is the same as in Aleph Explorer

src/aleph_client/__main__.py, src/aleph_client/asynchronous.py, src/aleph_client/exceptions.py, src/aleph_client/synchronous.py, src/aleph_client/types.py, src/aleph_client/utils.py, tests/integration/itest_posts.py, tests/integration/test_utils.py, tests/unit/test_utils.py
A user could not easily get a single message from the API server, with a clear error message when failing.
Solution: Add function `get_message` singular.
=> Feature: Could not get a single message easily

src/aleph_client/asynchronous.py, src/aleph_client/models.py
The code serving the API may return messages that are not valid according the latest version of the schemas. Ignore them with an optional log instead of failing the parsing of the entire response.
This is an alternative to https://github.com/aleph-im/aleph-message/pull/27 . Putting this logic in the client library allows users to add more options on how invalid messages should be handled.
=> Fix: Any invalid message in a response crashed the entire response

setup.cfg
This prevented us from uploading new versions on PyPI.
=> Fix: PyPI does not accept git dependencies

setup.cfg
Fix: aiohttp version was incompatible with Python 3.10
=> fixed aiohttp dependency [issue #117]

setup.cfg
Chore: aleph-client and pyaleph are not synchronized on substrate-interface version.
Solution: Update substrate-interface from LTS to 1.3.4.
related to: https://github.com/aleph-im/pyaleph/pull/358 on pyaleph.
=> Chore: fix substrate-interface version to 1.3.4

src/aleph_client/__main__.py
The command `aleph whoami` did not print the address used by the user.
```
$ aleph whoami
0x75aB2CDEd7981eD547BdCd1a9df2C5ccC8203D0F
$ git checkout master
Switched to branch 'master'
$ aleph whoami
0x031df8a6e3c2c1ab83b0ca937e12f02437108c239a2c60dbe62499a4429b2efb4e
```
This can be traced to a different behaviour, here for ethereum:
```python
def get_address(self) -> str:
return self._account.address
def get_public_key(self) -> str:
return "0x" + get_public_key(private_key=self._account.key).hex()
```
=> Fix: Command whoami printed public key, not address

src/aleph_client/asynchronous.py
Problem: submitting non-inline messages fails because the item type field is not set.
Solution: set the item type field for ipfs and storage item types.
=> Fix: item type is not set for non-inline messages

src/aleph_client/asynchronous.py, tests/unit/test_asynchronous.py
Problem: the `broadcast` function uses the now deprecated /ipfs/pubsub/pub/ endpoint.
Solution: use the new POST /messages/ endpoint. If the selected API server does not support the new endpoint, fall back to the previous implementation.
Used the occasion to clean up the broadcast error handling.
=> Feature: support the new POST /messages/ endpoint

src/aleph_client/asynchronous.py
Problem: There's no function to download storage data by its item hash (see issue #60)
Solution: Add get_store_file()
=> Feat: Get raw storage file (issue #60)

examples/httpgateway.py, examples/metrics.py, examples/store.py, src/aleph_client/asynchronous.py, src/aleph_client/commands/aggregate.py, src/aleph_client/commands/message.py, src/aleph_client/commands/program.py, src/aleph_client/conf.py, src/aleph_client/exceptions.py, src/aleph_client/synchronous.py, src/aleph_client/types.py, tests/integration/itest_aggregates.py, tests/integration/itest_forget.py, tests/integration/itest_posts.py, tests/unit/test_asynchronous.py
Problem: the broadcast function does not give enough information on the status of the broadcast operation. Some logs are printed but there is no way for the user to determine the status of the message processing + broadcast programmatically.
Solution: refactor the broadcast function so that:
1. it now returns the status of the message, if successful (pending or processed)
2. it raises a `BroadcastError` exception if the broadcast operation failed for some reason.
Renamed `broadcast` to `_broadcast` as it is now considered a private function.
=> Feature: refactor the broadcast function

src/aleph_client/chains/common.py, src/aleph_client/chains/ethereum.py, src/aleph_client/chains/sol.py, src/aleph_client/chains/tezos.py, tests/unit/conftest.py, tests/unit/test_asynchronous.py, tests/unit/test_chain_ethereum.py, tests/unit/test_chain_nuls1_compat.py, tests/unit/test_chain_solana.py, tests/unit/test_chain_tezos.py
Never delete private keys, as this could put the user at risk. Instead, use temporary files in tests.
=> Refactor: Private keys could be deleted

src/aleph_client/vm/cache.py
Problem: the aiohttp session is not required in this object. Solution: remove it from the base class constructor and use it only for the real VM cache.
=> Fix: remove aiohttp from TestVmCache __init__()

.github/workflows/test-build.yml, setup.cfg, src/aleph_client/__main__.py, src/aleph_client/commands/about.py, src/aleph_client/commands/account.py, src/aleph_client/commands/aggregate.py, src/aleph_client/commands/files.py, src/aleph_client/commands/message.py, src/aleph_client/commands/program.py, src/aleph_client/utils.py, tests/unit/test_commands.py
PR #164, which has recently been merged, used the latest main branch of `aleph-sdk-python`. There have been further breaking changes since the last CI/CD run of that PR, so a broken branch has mistakenly been merged into this repo's master branch.
This PR solves multiple issues:
- Use new `MessageFilter` and `PostFilter` properties and other changes to the `AlephClient` and `AuthenticatedAlephClient` interfaces.
- Introduce an `AsyncTyper` class to accommodate for the fact that `aleph-sdk-python` removed sync wrappers for the client classes.
- Fixes a MacOS CI/CD issue, forcing it to use Python 3.11 instead of 3.12.
=> Use latest post-v0.7.0 SDK - fix breaking changes

.github/workflows/test-build.yml
Fix test-build.yml to:
- only trigger on pushes to master
- trigger the workflow on any PR to master, this fixes @1yam's issues of forked repositories making a PR
`test-pytest.yml` remains the same, it will trigger on any push and on all PRs to master.
=> Fix `test_build.yml` workflow

setup.cfg, src/aleph_client/__main__.py, src/aleph_client/commands/account.py, src/aleph_client/commands/aggregate.py, src/aleph_client/commands/files.py, src/aleph_client/commands/node.py
**Problem:**
- Lot's of basic features was missing on Aleph CLI
**Solution:**
- Add those features:
**Account:**
- `aleph account balance` -> return current user balance or specific with `--address`
**File:**
- `aleph file list` -> return user file or specific of a specific address with `--address`
- `aleph file forget` -> forget a file
**Aggregate:**
- `aleph aggregate post` (used for update too)
- `aleph aggregate get`
**Node:**
- **Compute:**
- `aleph node compute` -> List all compute nodes
- **Core:**
- `aleph node core` -> List all core channel nodes
=> Feature: Add account, aggregate, node, file essential Functionality

.github/workflows/pr-rating.yml
Introducing automated PR difficulty rating.
See https://github.com/aleph-im/aleph-sdk-python/pull/76
=> PR Difficulty Rating Workflow

setup.cfg, src/aleph_client/commands/account.py, src/aleph_client/commands/files.py, src/aleph_client/commands/node.py
As we are now using `AsyncTyper`, we can freely use async `aiohttp`-style requests everywhere
=> Replace all usages of `requests` module with `aiohttp`

src/aleph_client/commands/account.py
1. **Wasn't allowed to simply send a private key**
2. **Encoding on file wasn't correct**
=> Fix: Importing account from private key wasn't possible

src/aleph_client/__main__.py
Having relative imports would break commands like:
```shell
typer ./src/aleph-client/__main__.py utils docs
```
Discovered when generating docs for https://github.com/aleph-im/aleph-docs/pull/75
=> Fix relative import in `__main__.py`

docker/Dockerfile, setup.cfg, src/aleph_client/commands/instance.py, src/aleph_client/conf.py
Problem: We cannot select the hypervisor to publish an instance, and the memory by default isn't the standard.
Solution: Add hypervisor field using firecracker by default and specify the default memory for instances.
=> Implement hypervisor field for instances

src/aleph_client/conf.py
The `example_fastapi` example in `aleph-vm` and the documentation require a newer version of the runtime.
This uses a new runtime, published by the same address and with the latest version of the SDK.
=> Fix: Recent example_fastapi versions requires newer runtime

src/aleph_client/__main__.py, src/aleph_client/commands/about.py, src/aleph_client/commands/account.py, src/aleph_client/commands/aggregate.py, src/aleph_client/commands/domain.py, src/aleph_client/commands/files.py, src/aleph_client/commands/instance.py, src/aleph_client/commands/message.py, src/aleph_client/commands/node.py, src/aleph_client/commands/program.py
Problem: Calling a command with no argument only displayed "Press --help for help".
Solution: Use a feature of Typer to display the help automatically when no argument is passed.
=> Fix: Passing to arg did not show help

src/aleph_client/commands/aggregate.py, src/aleph_client/commands/domain.py, src/aleph_client/commands/instance/__init__.py, src/aleph_client/commands/instance/display.py, src/aleph_client/commands/instance/network.py, src/aleph_client/commands/message.py, src/aleph_client/commands/node.py, src/aleph_client/commands/program.py, src/aleph_client/commands/utils.py, src/aleph_client/conf.py, src/aleph_client/models.py, tests/unit/test_instance.py, tests/unit/test_utils.py
Issue: Previously, users were unable to create PAYG instances from the CLI using a CRN.
Solution: Implemented a prompt to ask users if they want to create a PAYG instance,
displaying a list of compatible CRNs after an asynchronous fetching of the information.
Co-authored-by: Hugo Herter <git@hugoherter.com>
=> Fix: Unable to Create PAYG Instance from CLI

src/aleph_client/commands/instance/network.py
=> feat: add x.com to list of forbidden host

.github/workflows/pytest.yml, .github/workflows/test-build.yml
Let's try removing it to see if it fixes the CI.
I'm not sure we want to keep supporting this version.
Fixes: https://github.com/aleph-im/aleph-client/issues/219
=> ci: remove macOS 11 support

src/aleph_client/commands/instance/__init__.py, src/aleph_client/utils.py
Problem:
```aleph instance list``` only handles the Hold method.
Solution:
Check the payment type and fetch api_url and ipv6 from ```/about/executions/list.```
Changes:
- Added logic to check if there is a payment associated with the message.
- If there is no payment, the function fetches the VM details from the scheduler API.
- If there is a payment, the function fetches the server URL and retrieves the ipv6 address from the node's execution list
=> Refactor: Allow aleph instance list to handle PAYG

src/aleph_client/commands/instance/__init__.py
A list of small code refactoring for #228 
This should simplify the code and make it easier to read and extends.
I've removed some unused bits.
=> Small refactoring for PR #228 (Add `Qemu` working runtimes)

.github/workflows/pytest.yml, pyproject.toml, src/aleph_client/commands/instance/__init__.py, src/aleph_client/utils.py
**Note:** This pull request depends on the following PR and should not be merged before it:
[https://github.com/aleph-im/aleph-sdk-python/pull/124](https://github.com/aleph-im/aleph-sdk-python/pull/124)
This PR introduces new commands for managing virtual machine instances. These commands provide users with enhanced control over their VMs.
The following commands have been added:
1. **Notify Instance**: 
```shell
aleph instance notify {vm_id} {domain}
```
Sends a notification to the specified VM instance within the given domain.
2. **Stop Instance**:
```shell
aleph instance stop {vm_id} {domain}
```
Stops the specified VM instance within the given domain.
3. **Reboot Instance**:
```shell
aleph instance reboot {vm_id} {domain}
```
Reboots the specified VM instance within the given domain. …
=> Feature: Operator command for instance

src/aleph_client/commands/instance/__init__.py
Problem:
In the node_list, the addresses are stored inconsistently. Some nodes have addresses without a trailing slash, like:
``` json
"address": "https://acn-000060.nodeforge.io"
```
While others have addresses with a trailing slash:
``` json
"address": "https://aleph3.serverrg.eu/"
```
Solution:
Ensure consistent URL formatting by appending the path correctly, regardless of whether the address ends with a slash. This will prevent any issues caused by missing or double slashes when constructing URLs. The implementation will check if the last character of the address is a slash and adjust accordingly.
=> Fix: Ensure consistent URL formatting in _get_ipv6_address

pyproject.toml
This new merged PR broke aleph-client on Windows: https://github.com/aleph-im/aleph-client/pull/239
The only fix right now seems to be downgrading to 3.9.5, according to https://github.com/nathom/streamrip/issues/729
=> Fix: revert upgrade: aiohttp 3.10.2 -> 3.9.5

src/aleph_client/commands/instance/__init__.py
Solves https://github.com/aleph-im/aleph-client/issues/245
The function attempts to move a file from `/tmp`
to ~/.aleph-im/confidential_sessions .
This crashed if those were on a different
filesystem.
Replacing `pathlib.Path.rename` with `shutil.move` solves this issue as the later can handle this situation.
=> Fix: Cross-device links crashed 'confidential-init-session'

src/aleph_client/commands/instance/__init__.py
Instead of as option using --vm-id and --crn-url
This allow staying conistant with the other instance command targeting a VM
- [x ] The new code clear, easy to read and well commented.
`aleph instance confidential <vm_id> <crn_url>`
and 
`aleph instance confidential`
=> Confidential command: Pass hash vm_id and crn_url as argument

src/aleph_client/commands/instance/__init__.py, src/aleph_client/commands/instance/display.py, src/aleph_client/commands/instance/network.py, src/aleph_client/commands/message.py, src/aleph_client/commands/utils.py, src/aleph_client/conf.py, src/aleph_client/models.py, src/aleph_client/utils.py, tests/unit/test_instance.py
- Cleaning / rewritting / simplification of commands -> instance -> display.py / network.py
- Properly retrieve CRN data
- Fix broken CRNTable
- Add sort_by keys (score, name, version, address, coco, qemu, url)
- Add auto-filtering for reward address, qemu support and confidential support
Try to create a PAYG or coco instance without specifying crn_hash and crn_url. It will display the new CRNTable.
=> Fix CRNtable, sort_by keys, autofiltering on reward_add/qemu/coco

pyproject.toml
We don't have an upper hand version for our own dependency which mean we can't
safely release a breaking version of aleph-sdk-python because that would break
this package.
Set the max version of this dependency to inferior of the next major version.
Just install this version with pip (but the CI will do that for you)
=> fix(pyproject): max aleph-sdk-python versiont to respect semver

pyproject.toml, src/aleph_client/commands/message.py, src/aleph_client/commands/utils.py
When using aleph message get, it simply retrieves the message and does not return the status (and provides no information when it's rejected).
The documentation regarding the impacted features is available on:
> URL
The changes in the documentation are available here:
> URL
Usage of the new overload implemented in [PR](https://github.com/aleph-im/aleph-sdk-python/pull/163) to get the message status, and if the status is rejected, we retrieve the message error.
Install needed sdk parts
```shell
pip install git+https://github.com/aleph-im/aleph-sdk-python.git@1yam-message-status
```
```
aleph message get item_hash
```
This PR need [PR](https://github.com/aleph-im/aleph-sdk-python/pull/163) getting merged first
=> Refactor: aleph message get to handle message status

pyproject.toml
See https://github.com/aleph-im/aleph-client/pull/242
ALEPH-205
=> fix: don't use the buggy version of aiohttp on windows

README.md, scripts/gendoc.py
Related ClickUp, GitHub or Jira tickets : ALEPH-240
- [na ] The new code clear, easy to read and well commented.
- [na] New code does not duplicate the functions of builtin or popular libraries.
- [na] New classes and functions contain docstrings explaining what they provide.
- [na] All new code is covered by relevant tests.
=> docs: add instructions for updating user documentation during release

.github/workflows/pytest.yml, .github/workflows/test-build.yml, pyproject.toml, src/aleph_client/commands/account.py, src/aleph_client/commands/instance/__init__.py
Related Jira tickets : ALEPH-279
The documentation regarding the impacted features is available on:
> URL
The changes in the documentation are available here:
> URL
Changed the `aleph_message` dependency to use the last version with new EVM definitions.
Also changed the dependency of `aleph-sdk-python` to get the last version with new EVMs.
Set the account chain to one of the new ones and try to sign and send a message, like `"CHAIN": "POL"`.
This [PR](https://github.com/aleph-im/aleph-message/pull/116) should be merged before at the deployment time.
=> Implement new EVM chains

.github/workflows/pytest.yml, src/aleph_client/commands/help_strings.py, src/aleph_client/commands/utils.py
- name/mount are now required when providing volumes to an instance
- fix python version (3.13 -> 3.11) for macos 13/14 CI
=> Fix: name/mount required on instance's volumes + Fix macos CI

src/aleph_client/commands/instance/__init__.py
Related ClickUp, GitHub or Jira tickets : [ALEPH-291](https://aleph-im.atlassian.net/browse/ALEPH-291)
After changing the instance holding price, we need to put the same on the CLI also.
Also, I increased the limit of the disk size and RAM size, accordingly to the new limits.
Try to create a normal instance, holding and PAYG and check that the balance required is the half of before.
=> Reduce instance PAYG balance to half

src/aleph_client/commands/instance/__init__.py, src/aleph_client/commands/instance/network.py, src/aleph_client/commands/program.py, src/aleph_client/utils.py, tests/unit/test_instance.py
Replace #299 because the previous branch name was preventing the CI from working properly, and I can't change the branch name inside an existing PR
Get more information on program boot
Add a command 'aleph program logs' to retrive program logs and help debugging them
To be used with https://github.com/aleph-im/aleph-vm/pull/718
Related ClickUp, GitHub or Jira tickets : ALEPH-275
*VMClient2 should be moved in the SDK but I'm putting it there for now so it's easier to test and debug.*
=> add `aleph program logs`

src/aleph_client/commands/instance/__init__.py
The `-i` option in `ssh` is used to specify the path to the private key file, not the public one
=> fix(commands/instance): Wrong ssh option description

pyproject.toml, src/aleph_client/commands/help_strings.py, src/aleph_client/commands/instance/__init__.py, src/aleph_client/commands/instance/display.py, src/aleph_client/models.py, tests/unit/test_instance.py
Problem: If a user wants to select a GPU to assign it to a VM, he cannot do it.
Solution: Allow to get available GPUs from the CRN forcing the user to select it and allow assign it to a VM.
Try to create an instance assigning a GPU. To be able to do it you will need to specify a CRN with GPUs available and a CRN hash, this can be solved attaching that arguments to the instance creation command: `--gpu --crn-url https://gpu-test-02.nergame.app/ --crn-hash 9ba6bd307ce7631b7e7cc5e2bed6285230ff405b1c8060d2a4318781d3552d71`
=> Implement GPU support

pyproject.toml, src/aleph_client/commands/program.py, tests/unit/test_commands.py
Endpoint name was changed in the aleph-vm PR but this was not reflected here.\
Also move the operate method inside the python sdk
Related ClickUp, GitHub or Jira tickets : continuation of  ALEPH-275
Launch a function you control on a CRN.
Then use `aleph  program logs <item hash> --domain <crn_url>`
=> Fix program logs command

src/aleph_client/commands/instance/network.py, src/aleph_client/commands/node.py, src/aleph_client/utils.py, tests/unit/mocks.py, tests/unit/test_node.py
=> Fix bugs on aleph node cmds + sanitize_url + missing tests

src/aleph_client/commands/program.py
=> Fix program indications for list/persist/unpersist commands

src/aleph_client/commands/instance/__init__.py
Jira: None
- Fix: `aleph instance list` was displaying "Boot uninitialized/unstarted confidential instances with..." not only on coco, but also for all unallocated instances
=> Fix unwanted uninit coco vm msg on instance list

src/aleph_client/__main__.py, src/aleph_client/commands/aggregate.py, src/aleph_client/commands/help_strings.py, tests/unit/mocks.py, tests/unit/test_aggregate.py
Jira: [ALEPH-402](https://aleph-im.atlassian.net/browse/ALEPH-402)
Try out all commands
=> Fix & Improve aggregates + Add permission commands

src/aleph_client/commands/instance/__init__.py, src/aleph_client/commands/instance/display.py, tests/unit/test_instance.py
=> Improve GPU selection

README.md, src/aleph_client/commands/account.py, src/aleph_client/commands/help_strings.py, tests/unit/test_commands.py
The command `aleph account create` did not permit users to import their private key encoded in base32 or base64.
This adds the `--key-format` argument to the command to specify this.
=> Fix: Could not import private key in base32/base64

src/aleph_client/commands/files.py
This pull request introduces error handling for the `upload` function in `src/aleph_client/commands/files.py` to provide more informative feedback when file uploads fail. It also includes a minor import statement update.
* Added a `try-except` block in the `upload` function to catch `ClientResponseError` exceptions during file uploads. This ensures that specific error messages are displayed to the user, such as notifying them when a file is too large to upload (`status: 413`) or providing a generic error message for other cases. [[1]](diffhunk://#diff-bad7d12698031f8051164cfd445a71f962fa9ed9c51b124d12813502cac2d813R92) [[2]](diffhunk://#diff-bad7d12698031f8051164cfd445a71f962fa9ed9c51b124d12813502cac2d813R102-R108)
* Imported `ClientResponseError` from `aiohttp` to support the new error …
=> Fix: missing try catch on aleph file upload

src/aleph_client/commands/instance/display.py
Fix: Relax CRN version check to use custom release also for confidentials and PAYG.
=> Relax CRN version check for Confidentials and PAYG

src/aleph_client/commands/message.py, src/aleph_client/commands/pricing.py, src/aleph_client/commands/utils.py, tests/unit/test_commands.py
This PR add the handling of the two new status `REMOVING` and `REMOVED`
Related ClickUp, GitHub or Jira tickets : ALEPH-573
- [] New classes and functions contain docstrings explaining what they provide.
- [] All new code is covered by relevant tests.
This pull request adds support for handling messages that are in the process of being removed or have already been removed on aleph.im. It improves error handling and status reporting for these new message states.
**Error handling improvements:**
* Added `RemovedMessageError` to the list of exceptions handled in `message.py`, allowing the CLI to inform users when a message has been removed.
* Updated the `get` command to catch `RemovedMessageError` and display an appropriate message to the user.
**Status reporting enhancements:**
* Modified …
=> Feature: Handle `REMOVING` and `REMOVED` status
